[package]
name = "keyboard_win"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "A mini tools for Windows keyboard by winapi"


[dependencies]
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }